### ISSUE TITLE
Delete readme_example.yml workflow?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-k3s-helm#12]
@manics what do you think about deleting the dedicated workflow for the example in the README?

I think we have sufficient tests to capture whatever we put in the README.md in general, but if we want to verify that example works specifically, we could perhaps put it as one matrix case in the test workflow?

**Comment by manics** [comment]
My intention was to eventually have a check somewhere that asserts the content of the readme example is _exactly_ identical to the contents of https://github.com/jupyterhub/action-k3s-helm/blob/main/.github/workflows/readme_example.yml

This is to guard against the README example getting out of date- in the docs for other Jupyter repos there have been several examples of out date code which has ended up broken, but has only been picked up by people trying and failing to get them to work.

If you think it's too much trouble we could delete the workflow though. I don't think it's worth adding a matrix case as they key feature is the workflow as a whole.

**Comment by consideRatio** [comment]
Not much trouble! I wish I could make it trigger only on README.md changes but then we would not copy it as a whole properly though haha ;)
