### ISSUE TITLE
Additional output: k3s, k8s, and helm verions

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-k3s-helm#14]
It could be nice to get information about the installed k3s, k8s, and helm version as outputs of the action. It is a pre-optimization that I figure could be worth it.

Example outputs:
- k3s-version: v1.20.0+k3s2
- k8s-version: v1.20.0
- helm-version v3.4.2

Ideas on how to get the version numbers:
- `k3s --version | sed 's/.*\(v[0-9][^ ]*\).*/\1/'`
  The output is typically `k3s version v1.2.3+k3s4 (hashhash)`, the `sed` part is to extract what starts with `v` followed by a digit until a space shows up.
- `kubectl version --output=json | jq -r '.serverVersion.gitVersion'`
  One could take it directly from k3s-version, but the `kubectl version` request is instant when located on the same machine pretty much so I figure it makes more sense to go straight for the source info.
- `helm version --short`

@manics does this sound okay to you?

**Comment by manics** [comment]
Sounds fine to me!
