### ISSUE TITLE
Publish on GitHub Marketplace?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-k3s-helm#22]
It would be fun to publish this on the GitHub marketplace, but I was too tired to read through the legal stuff in [the agreement](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-marketplace-developer-agreement) that we as a GitHub org must accept.

Any thoughts?

**Comment by manics** [comment]
I added it when it was under my account https://github.com/marketplace/actions/k3s-with-calico-and-helm

Though it's saying `v0.2.2` is the latest version, so maybe something else needs to be switched?

**Comment by manics** [comment]
If you don't have any ideas maybe we should open a GitHub support ticket?

**Comment by consideRatio** [comment]
Sorry for slow response! Technically what needs to be done is that we visit https://github.com/jupyterhub/action-k3s-helm/releases/new and accept the agreement. But, I must do it for the entire JupyterHub org so its a question larger than the repo.

I'll open a team compass issue about it.

**Comment by consideRatio** [comment]
I opened https://github.com/jupyterhub/team-compass/issues/366

**Comment by consideRatio** [comment]
Published!
