### ISSUE TITLE
action fails for kubernetes v1.16

### ISSUE THREAD

**Issue by xopham** [jupyterhub/action-k3s-helm#37]
### Bug description
We use the GitHub Action for testing [Connaisseur](https://sse-secure-systems.github.io/connaisseur/latest) -- an admission controller to integrate container image signature verification and trust pinning into a cluster -- on different Kubernetes versions via the `k3s-channel` flag to test compatibility. When configured to use the `v1.16` as `k3s-channel`, installation of the k3s cluster fails as calico does not spin up and testing its availability times out.

#### Expected behaviour
The action should work with `v1.16` and be able to create the cluster.

#### Actual behaviour
It simply fails.

### How to reproduce
Simply implement the basic github action using `v1.16` for the `k3s-channel` as shown [here](https://github.com/sse-secure-systems/connaisseur/blob/test/test-k8s-v1.16/.github/workflows/cicd.yaml#L271):

```yaml
  test-k8s-v1_16:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-channel: v1.16
```
It fails with the following [logs](https://github.com/sse-secure-systems/connaisseur/runs/3846716902?check_suite_focus=true):

```bash
Run echo "::group::Wait for daemonset/calico-node"
  echo "::group::Wait for daemonset/calico-node"
  kubectl rollout status --watch --timeout 300s daemonset/calico-node -n kube-system
  echo "::endgroup::"
  
  echo "::group::Wait for deployment/calico-kube-controllers"
  kubectl rollout status --watch --timeout 300s deployment/calico-kube-controllers -n kube-system
  echo "::endgroup::"
  
  echo "::group::Wait for deployment/coredns"
  kubectl rollout status --watch --timeout 300s deployment/coredns -n kube-system
  echo "::endgroup::"
  
  echo "::group::Wait for deployment/metrics-server"
  if [[ "true" == true ]]; then
    kubectl rollout status --watch --timeout 300s deployment/metrics-server -n kube-system
  fi
  echo "::endgroup::"
  
  echo "::group::Wait for deployment/traefik"
  if [[ "true" == true ]]; then
    # NOTE: Different versions of k3s install traefik in different ways,
    #       by waiting for these jobs if they exist, we will be fine no
    #       matter what.
    kubectl wait --for=condition=complete --timeout=300s job/helm-install-traefik-crd -n kube-system || true
    kubectl wait --for=condition=complete --timeout=300s job/helm-install-traefik -n kube-system || true
    kubectl rollout status --watch --timeout 300s deployment/traefik -n kube-system
  fi
  echo "::endgroup::"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    KUBECONFIG: /home/runner/.kube/config
Wait for daemonset/calico-node
  Waiting for daemon set spec update to be observed...
  Waiting for daemon set "calico-node" rollout to finish: 0 out of 1 new pods have been updated...
  Waiting for daemon set "calico-node" rollout to finish: 0 of 1 updated pods are available...
  error: timed out waiting for the condition
  Error: Process completed with exit code 1.
```

### Your personal set up
Our full setup for the action can be seen in the GitHub Actions of [Connaisseur k8s version tests](https://github.com/sse-secure-systems/connaisseur/blob/develop/.github/workflows/cicd.yaml#L233) using [this sub-action](https://github.com/sse-secure-systems/connaisseur/blob/develop/.github/actions/k8s-version-config/action.yaml#L16).

### Problem and Solution
One could either fix the Calico Issue or even make Calico optional/configurable, as it is e.g. not required for our version tests...

### Thanks!
Thanks for sharing the awesome GitHub Action :pray: it really made version testing for Kubernetes easy. Keep it up :muscle:

**Comment by manics** [comment]
We made a breaking change in `v2` to drop support for 1.16: https://github.com/jupyterhub/action-k3s-helm/blob/main/CHANGELOG.md
It looks like the README wasn't updated though, I'll fix that.

`v1` should continue to work with 1.16.

**Comment by xopham** [comment]
Thanks for the prompt reply! Works nicely :slightly_smiling_face:
